<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading"><?= $this->get('page.title') ?></h1>
        <p class="lead text-muted"><?= $this->get('page.subtitle') ?></p>
        <p>
            <a href="/doc/index.html" class="btn btn-tertiary my-2">view documentation</a>
        </p>
    </div>
</section>
<main class="container">
    <div class="row">
        <div class="col-sm-12 markdown-body">
            <h1 id="introduction">Introduction</h1>
            <h2 id="why">Why?</h2>
            <p>You may ask yourself: why did those guys bothered with another PHP framework? The answer is quite simple: we're bored with spending more times understanding and masterizing the framework itself than with working on the actual applications features.</p>
            <p><strong>productivity</strong> is the main target of Objective PHP</p>
            <p>On top of that, we thought that working on a new framework would also be an opportunity to consider performances in a different way. Most frameworks rely on cache to offer decent performances. Well, cache can help. A bit. But once you cached the poor performing components, what more can you do? Nothing.</p>
            <p><strong>performance</strong> is the second major concern of Objective PHP</p>
            <h2 id="what">What?</h2>
            <p>Objective PHP is a lightweight framework written in PHP7 with OOP in mind. This is why it's called that - there is other reason, except a pun on Objective C of course :)</p>
            <p>Is Objective PHP a fullstack framework? Is it a micro-framework? Actually, neither. We use to call it a mini-framework, meaning that it's somewhere in between: it provides the developers with much more than a micro-framework does, but also less than a fullstack.</p>
            <p>Objective PHP aims at handling applicative workflows, then let the developer do their work. No more, no less.</p>
            <p>For higher level components, like Forms generators or ORMs for instance, we thought that it would be more efficient to let developers bring their usual tools in Objective rather than forcing them to use our own alternatives.</p>
            <h2 id="how">How?</h2>
            <p>The key idea to help developers getting efficient and comfortable with Objective PHP is to reduce as much as possible the number of different mechanism to achieve essential tasks the framework has to handle.</p>
            <p>After many tries, we came down to a combination of two central concepts:</p>
            <ul>
                <li><em>Middlewares</em> to set up a workflow</li>
                <li><em>Events</em> to ease the connexion between the application components</li>
            </ul>
            <br/>
        </div>
    </div>
</main>

