<?php
use ObjectivePHP\Application\Config\ApplicationName;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?= $this->param(ApplicationName::KEY) ?></title>
        <link href="/assets/style.css" rel="stylesheet">
        <script src="/assets/jquery-3.3.1.min.js"></script>

    </head>
    <body role="document">
        <?php include __DIR__ . '/partials/navbar.phtml'; ?>

        <?= $this->getViewOutput();  ?>

        <script src="/assets/theme.js"></script>
        <script src="/assets/dev.js"></script>
    </body>
</html>

