<?php

use ObjectivePHP\Application\Config\ApplicationName;

$partial = __DIR__ . '/partials/';
$asset = json_decode(file_get_contents(__DIR__ . '/../../public/dist/manifest.json'), true);
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?= $this->param(ApplicationName::KEY) ?></title>
        <link href="/dist/<?= $asset['theme.css'] ?>" rel="stylesheet">
    </head>
    <body role="document">
        <?php include $partial . 'navbar.phtml' ?>

        <?= $this->getViewOutput()  ?>

        <?php include $partial . 'footer.phtml' ?>

        <script src="/dist/<?= $asset['app.js'] ?>"></script>
    </body>
</html>

