<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col subscriptions">
                <p>Subscribe to Objective PHP</p>
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="https://github.com/objective-php" target="_blank"><i class="fa fa-github"></i></a>
                    </li>
<!--                    <li class="list-inline-item">-->
<!--                        <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>-->
<!--                    </li>-->
                </ul>
            </div>
        </div>
    </div>
</footer>