<?php

use ObjectivePHP\Application\Config\ApplicationName;

?>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">
        <img src="/assets/img/brand.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <?= $this->param(ApplicationName::KEY) ?>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <?php foreach ($this->get('navbar-main-menu') as $page) : ?>
            <li class="nav-item">
                <a class="nav-link <?= $page['active'] ?>" href="<?= $page['url'] ?>"><?= $page['name'] ?></a>
            </li>
            <?php endforeach; ?>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="http://github.com/objective-php" target="_blank">Objective PHP on GitHub</a>
            </li>
        </ul>
    </div>
</nav>
